In [3]:
!pip install selenium

'pip' is not recognized as an internal or external command,
operable program or batch file.

In [6]:
#car dekho data taking by web scraping method
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

import time

# Setup Chrome WebDriver
driver = webdriver.Chrome()

# Open the CarDekho website
driver.get('https://www.cardekho.com/used-cars+in+bangalore')

# Wait for the page to load (adjust as necessary)
time.sleep(5)
bengalure = driver.find_elements(By.XPATH, "//div[@class='gsc_col-xs-12 gsc_col-sm-6 gsc_col-md-4 cardColumn']")

for i in bengalure:
    print(i.text)

2024 Force Gurkha 2.6 Diesel
2,000 kms   •   Diesel   •   Manual
₹18.50 Lakh
Compare
View Seller Details
Indiranagar, Bangalore
2016 Maruti Alto K10 VXI AMT
52,480 kms   •   Petrol   •   Automatic
₹3.28 Lakh
Compare
View Seller Details
Jakkur, Bangalore
2022 Kia Carens Luxury Plus 6 STR Diesel
56,000 kms   •   Diesel   •   Manual
₹17.25 Lakh
Compare
View Seller Details
R T Nagar, Bangalore
2022 Kia Seltos HTX Diesel
40,000 kms   •   Diesel   •   Manual
₹17 Lakh
Compare
View Seller Details
Nandagudi, Bangalore
2024 Kia Seltos GTX Plus Turbo DCT
8,300 kms   •   Petrol   •   Automatic
₹20.65 Lakh
Compare
₹21.25 Lakh(Save ₹60,000)
View Seller Details
Adugodi, Bangalore
2018 Hyundai Grand i10 1.2 Kappa Sportz BSIV
17,817 kms   •   Petrol   •   Manual
₹5.57 Lakh
Compare
View Seller Details
Samethanahalli, Bangalore
2016 Honda Jazz 1.2 V i VTEC
67,943 kms   •   Petrol   •   Manual
₹4.39 Lakh
Compare
₹4.54 Lakh(Save ₹15,330)
View Seller Details
Richmond Town, Bangalore
2022 Kia Seltos HTK G
9,536 kms   •   Petrol   •   Manual
₹11.72 Lakh
Compare
₹12.34 Lakh(Save ₹61,780)
View Seller Details
Avalahalli, Bangalore
Don’t want to go far?
Find all cars near me
Find cars near me
Use Current Pincode
2017 Mercedes-Benz GLE 43 AMG Coupe
59,956 kms   •   Petrol   •   Automatic
₹61.99 Lakh
Compare
View Seller Details
City, Bangalore
2022 MG Astor Sharp Turbo AT BSVI
9,348 kms   •   Petrol   •   Automatic
₹15.45 Lakh
Compare
View Seller Details
Bellandur, Bangalore
2014 Hyundai Verna 1.6 SX VTVT
52,500 kms   •   Petrol   •   Manual
₹6.25 Lakh
Compare
View Seller Details
Bazaar, Bangalore
2023 Renault KWID 1.0 RXT AMT
6,184 kms   •   Petrol   •   Automatic
₹5.37 Lakh
Compare
₹6.12 Lakh(Save ₹75,000)
View Seller Details
Mahadevapura, Bangalore
2012 BMW 3 Series 320i Touring
80,000 kms   •   Petrol   •   Automatic
₹8 Lakh
Compare
View Seller Details
Bangalore
2016 Honda Jazz 1.2 S i VTEC
36,465 kms   •   Petrol   •   Manual
₹6.25 Lakh
Compare
View Seller Details
City, Bangalore
2021 MG Hector Sharp CVT
34,900 kms   •   Petrol   •   Automatic
₹16.75 Lakh
Compare
View Seller Details
Bellandur, Bangalore
2022 BMW X3 xDrive20d xLine
12,000 kms   •   Diesel   •   Automatic
₹69 Lakh
Compare
View Seller Details
R T Nagar, Bangalore
2019 Honda Amaze V CVT Petrol BSIV
90,000 kms   •   Petrol   •   Automatic
₹5.50 Lakh
Compare
View Seller Details
Bangalore
2019 Honda Amaze V CVT Petrol BSIV
16,000 kms   •   Petrol   •   Automatic
₹6.95 Lakh
Compare
View Seller Details
Gottigere, Bangalore
2016 Hyundai Grand i10 Asta
19,771 kms   •   Petrol   •   Manual
₹4.77 Lakh
Compare
₹5.20 Lakh(Save ₹43,000)
View Seller Details
Magadi Road, Bangalore
2022 Hyundai Venue SX BSVI
14,112 kms   •   Petrol   •   Manual
₹10.99 Lakh
Compare
View Seller Details
Bellandur, Bangalore

In [10]:
pip install pandas

Collecting pandas
  Downloading pandas-2.2.3-cp311-cp311-win_amd64.whl (11.6 MB)
     -------------------------------------- 11.6/11.6 MB 363.1 kB/s eta 0:00:00
Collecting numpy>=1.23.2
  Downloading numpy-2.2.2-cp311-cp311-win_amd64.whl (12.9 MB)
     -------------------------------------- 12.9/12.9 MB 221.4 kB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hari vignesh\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1
  Downloading pytz-2024.2-py2.py3-none-any.whl (508 kB)
     ------------------------------------ 508.0/508.0 kB 165.9 kB/s eta 0:00:00
Collecting tzdata>=2022.7
  Downloading tzdata-2025.1-py2.py3-none-any.whl (346 kB)
     ------------------------------------ 346.8/346.8 kB 336.5 kB/s eta 0:00:00
Requirement already satisfied: six>=1.5 in c:\users\hari vignesh\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-2.2.2 pandas-2.2.3 pytz-2024.2 tzdata-2025.1
Note: you may need to restart the kernel to use updated packages.

  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'c:\Users\Hari Vignesh\AppData\Local\Programs\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip available: 22.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time

# Ensure the browser window remains open
driver = webdriver.Chrome()
driver.get('https://www.cardekho.com/used-cars+in+bangalore')
time.sleep(5)

# Scroll until the end of the page
last_height = driver.execute_script("return document.body.scrollHeight")  # Get initial page height

while True:
    # Scroll down
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(5)  # Wait for the page to load more content

    # Get the new page height
    new_height = driver.execute_script("return document.body.scrollHeight")

    # Break the loop if the page height hasn't changed (end of the page)
    if new_height == last_height:
        time.sleep(5)
        break

    last_height = new_height
    
# Find the elements containing the car details
bengalure = driver.find_elements(By.XPATH, "//div[@class='gsc_col-xs-12 gsc_col-sm-6 gsc_col-md-4 cardColumn']")

# Extract the text content of the elements
bengalure_car_details = [i.text for i in bengalure]

# Close the browser
driver.quit()

# Initialize the list to store structured data
structured_data = []

# Loop through the extracted car details
for detail in bengalure_car_details:
    # Split the details by lines
    lines = detail.split("\n")
    
    # Extract key information
    try:
        # Split the first line into year and car name
        year_and_name = lines[0].split(" ", 1)
        year = year_and_name[0]  # Year
        car_name = year_and_name[1]  # Car name
        
        # Extract mileage, fuel, transmission (safely handle cases where data is missing or incomplete)
        if "•" in lines[1]:
            details = [item.strip() for item in lines[1].split("•")]
            if len(details) == 3:
                mileage, fuel_type, transmission = details
            elif len(details) == 2:
                mileage, fuel_type = details
                transmission = ""
            else:
                mileage = details[0]
                fuel_type = transmission = ""
        else:
            mileage = fuel_type = transmission = ""
        
        mileage = mileage.replace("kms", "").strip()  # Clean mileage text
        
        # Extract price (safely handle missing data)
        price = lines[2].replace("₹", "").replace("Lakh", "").strip() if len(lines) > 2 else ""
        
        # Extract location (last line)
        location = lines[-1] if len(lines) > 3 else ""
        
        # Append structured data
        structured_data.append({
            "Year": year,
            "Car Name": car_name,
            "Mileage (kms)": mileage,
            "Fuel Type": fuel_type,
            "Transmission": transmission,
            "Price (Lakh)": price,
            "Location": location
        })
    except Exception as e:
        print(f"Error processing detail: {detail}\nError: {e}")

# Create DataFrame
car_df = pd.DataFrame(structured_data)

# Save to CSV
car_df.to_csv('bengalure_car_details.csv', index=False)

# Print DataFrame
print(car_df)

      Year                                    Car Name Mileage (kms)  \
0     2014                      Mahindra XUV500 W8 FWD        89,000
1     2015                        Hyundai i20 Asta 1.2        72,811
2     2015                       Maruti Swift VDI BSIV      1,06,000
3     2022  Volkswagen Taigun 1.0 TSI Highline AT BSVI         8,951
4     2024               Kia Seltos GTX Plus Turbo DCT         8,300
...    ...                                         ...           ...
2896  2012                             Honda Brio S MT        63,446
2897  2021                        Renault KWID 1.0 RXE        15,161
2898  2022                     Toyota Hyryder V HYBRID        19,934
2899  2018                  Tata Tiago 1.2 Revotron XZ      1,08,949
2900  2017                Renault KWID Climber 1.0 AMT        48,113

     Fuel Type Transmission Price (Lakh)                           Location
0       Diesel       Manual         7.40           Nagadenahalli, Bangalore
1       Petrol       Manual         5.03             Magadi Road, Bangalore
2       Diesel       Manual         4.95        Ramamurthy Nagar, Bangalore
3       Petrol    Automatic        13.51                  Jakkur, Bangalore
4       Petrol    Automatic        20.65                 Adugodi, Bangalore
...        ...          ...          ...                                ...
2896    Petrol       Manual            3              BTM Layout, Bangalore
2897    Petrol       Manual         4.21  Kengiri Satellite Town, Bangalore
2898    Petrol    Automatic        18.57               Bellandur, Bangalore
2899    Petrol       Manual         3.65               Yelahanka, Bangalore
2900    Petrol    Automatic         3.69                  Jakkur, Bangalore

[2901 rows x 7 columns]

In [7]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time

# Ensure the browser window remains open
driver = webdriver.Chrome()
driver.get('https://www.cardekho.com/used-cars+in+hyderabad')
time.sleep(5)

# Scroll until the end of the page
last_height = driver.execute_script("return document.body.scrollHeight")  # Get initial page height

scroll_attempts = 0
while True:
    # Scroll down
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(3)  # Allow time for new content to load

    # Get the new page height
    new_height = driver.execute_script("return document.body.scrollHeight")

    # Check if we have reached the bottom
    if new_height == last_height:
        scroll_attempts += 1  # Increment if no new data loads
        if scroll_attempts > 5:  # Stop after 5 attempts to load more content
            break
    else:
        scroll_attempts = 0  # Reset attempts if new content is loaded

    last_height = new_height

# Find the elements containing the car details
hyderabad = driver.find_elements(By.XPATH, "//div[@class='gsc_col-xs-12 gsc_col-sm-6 gsc_col-md-4 cardColumn']")

# Extract the text content of the elements
hyderabad_car_details = [i.text for i in hyderabad]

# Close the browser
driver.quit()

# Initialize the list to store structured data
structured_data = []

# Loop through the extracted car details
for detail in hyderabad_car_details:
    # Split the details by lines
    lines = detail.split("\n")
    
    # Extract key information
    try:
        # Split the first line into year and car name
        year_and_name = lines[0].split(" ", 1)
        year = year_and_name[0]  # Year
        car_name = year_and_name[1]  # Car name
        
        # Extract mileage, fuel, transmission (safely handle cases where data is missing or incomplete)
        if "•" in lines[1]:
            details = [item.strip() for item in lines[1].split("•")]
            if len(details) == 3:
                mileage, fuel_type, transmission = details
            elif len(details) == 2:
                mileage, fuel_type = details
                transmission = ""
            else:
                mileage = details[0]
                fuel_type = transmission = ""
        else:
            mileage = fuel_type = transmission = ""
        
        mileage = mileage.replace("kms", "").strip()  # Clean mileage text
        
        # Extract price (safely handle missing data)
        price = lines[2].replace("₹", "").replace("Lakh", "").strip() if len(lines) > 2 else ""
        
        # Extract location (last line)
        location = lines[-1] if len(lines) > 3 else ""
        
        # Append structured data
        structured_data.append({
            "Year": year,
            "Car Name": car_name,
            "Mileage (kms)": mileage,
            "Fuel Type": fuel_type,
            "Transmission": transmission,
            "Price (Lakh)": price,
            "Location": location
        })
    except Exception as e:
        print(f"Error processing detail: {detail}\nError: {e}")

# Create DataFrame
car2_df = pd.DataFrame(structured_data)

# Save to CSV
car2_df.to_csv('hyderabad_car_details.csv', index=False)

# Print DataFrame
print(car2_df)

     Year                                  Car Name Mileage (kms) Fuel Type  \
0    2018           Maruti S Cross Zeta DDiS 200 SH        92,650    Diesel
1    2019           Mercedes-Benz CLA 200 CDI Sport         6,000    Diesel
2    2020                 BMW X1 sDrive 20d M Sport        40,000    Diesel
3    2021  Mahindra Thar LX 4WD Convert Top AT BSVI        14,474    Petrol
4    2019    Ford Ecosport 1.5 Diesel Titanium BSIV      1,28,542    Diesel
..    ...                                       ...           ...       ...
776  2018      Skoda Rapid 1.5 TDI AT Ambition BSIV        73,323    Diesel
777  2020                Volkswagen Polo GT 1.0 TSI        28,000    Petrol
778  2011          Hyundai Verna 1.6 SX VTVT (O) AT        76,000    Petrol
779  2011          Volkswagen Vento Petrol Highline        75,000    Petrol
780  2019         Skoda Rapid 1.5 TDI Ambition BSIV        81,223    Diesel

    Transmission Price (Lakh)                Location
0         Manual         8.35        Nagol, Hyderabad
1      Automatic           33  Mehdipatnam, Hyderabad
2      Automatic           29  Mehdipatnam, Hyderabad
3      Automatic        12.30        Nagol, Hyderabad
4         Manual         7.95        Nagol, Hyderabad
..           ...          ...                     ...
776    Automatic         6.50        Nagol, Hyderabad
777    Automatic         8.95               Hyderabad
778    Automatic         3.90     LB Nagar, Hyderabad
779       Manual         2.45  Mehdipatnam, Hyderabad
780       Manual         6.90   Rangareddi, Hyderabad

[781 rows x 7 columns]

In [15]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
import time

# Initialize WebDriver
driver = webdriver.Chrome()
driver.get("https://www.cardekho.com/used-cars+in+chennai")  # Chennai Cars Page
time.sleep(5)  # Allow page to load

# Scroll until the end of the page
last_height = driver.execute_script("return document.body.scrollHeight")  # Get initial page height
scroll_attempts = 0

while True:
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(3)  # Allow time for new content to load
    
    new_height = driver.execute_script("return document.body.scrollHeight")
    if new_height == last_height:
        scroll_attempts += 1
        if scroll_attempts > 5:  # Stop after 5 failed attempts to load more content
            break
    else:
        scroll_attempts = 0  # Reset if new content loads

    last_height = new_height

# Find elements containing car details
car_elements = driver.find_elements(By.XPATH, "//div[@class='gsc_col-xs-12 gsc_col-sm-6 gsc_col-md-4 cardColumn']")

# Extract the text content from elements
car_details = [car.text for car in car_elements]

# Close the browser
driver.quit()

# Initialize list for structured data
structured_data = []

# Process extracted details
for detail in car_details:
    lines = detail.split("\n")  # Split text into lines
    
    try:
        year_and_name = lines[0].split(" ", 1)  # Extract Year and Car Name
        year = year_and_name[0]
        car_name = year_and_name[1]
        
        if "•" in lines[1]:
            details = [item.strip() for item in lines[1].split("•")]
            if len(details) == 3:
                mileage, fuel_type, transmission = details
            elif len(details) == 2:
                mileage, fuel_type = details
                transmission = ""
            else:
                mileage = details[0]
                fuel_type = transmission = ""
        else:
            mileage = fuel_type = transmission = ""
        
        mileage = mileage.replace("kms", "").strip()  # Clean mileage
        
        price = lines[2].replace("₹", "").replace("Lakh", "").strip() if len(lines) > 2 else ""
        
        location = lines[-1] if len(lines) > 3 else ""
        
        structured_data.append({
            "Year": year,
            "Car Name": car_name,
            "Mileage (kms)": mileage,
            "Fuel Type": fuel_type,
            "Transmission": transmission,
            "Price (Lakh)": price,
            "Location": location
        })
    except Exception as e:
        print(f"Error processing detail: {detail}\nError: {e}")

# Create DataFrame
car_df = pd.DataFrame(structured_data)

# Save to CSV
car_df.to_csv('chennai_used_cars.csv', index=False)

# Print DataFrame
print(car_df)

     Year                                      Car Name Mileage (kms)  \
0    2023                        Tata Tiago XZ Plus CNG         2,900
1    2014                      Honda City i VTEC CVT SV        77,259
2    2019                   Maruti Baleno 1.2 CVT Alpha        17,822
3    2022                    Tata Nexon 1.2 Revotron XM        43,206
4    2022  Hyundai Alcazar Signature (O) Diesel AT BSVI        20,000
..    ...                                           ...           ...
436  2018                    Maruti Swift Dzire AMT ZXI        47,618
437  2016          Volkswagen Vento 1.2 TSI Highline AT        70,000
438  2016              Ford Endeavour Titanium Plus 4X4      2,20,000
439  2020                   Renault KWID Climber 1.0 MT        41,000
440  2012                            Hyundai i10 Sportz        51,000

    Fuel Type Transmission Price (Lakh)                  Location
0         CNG       Manual         8.20                   Chennai
1      Petrol    Automatic         5.14   Ganapathipuram, Chennai
2      Petrol    Automatic         6.91   Ganapathipuram, Chennai
3      Petrol       Manual         8.20     Meenambakkam, Chennai
4      Diesel    Automatic        18.50                   Chennai
..        ...          ...          ...                       ...
436    Petrol    Automatic         5.84       Vadapalani, Chennai
437    Petrol    Automatic            6  Thygaraya Nagar, Chennai
438    Diesel    Automatic        18.50       Ashoknagar, Chennai
439    Petrol       Manual         4.35       Anna Nagar, Chennai
440    Petrol       Manual         3.25       Anna Nagar, Chennai

[441 rows x 7 columns]

In [7]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
import time

# Initialize WebDriver
driver = webdriver.Chrome()
driver.get("https://www.cardekho.com/used-cars+in+ahmedabad") 
driver.maximize_window()
time.sleep(5)  # Allow page to load

# Scroll until the end of the page
last_height = driver.execute_script("return document.body.scrollHeight")  # Get initial page height
scroll_attempts = 0

while True:
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(3)  # Allow time for new content to load
    
    new_height = driver.execute_script("return document.body.scrollHeight")
    if new_height == last_height:
        scroll_attempts += 1
        if scroll_attempts > 5:  # Stop after 5 failed attempts to load more content
            break
    else:
        scroll_attempts = 0  # Reset if new content loads

    last_height = new_height

# Find elements containing car details
car_elements = driver.find_elements(By.XPATH, "//div[@class='gsc_col-xs-12 gsc_col-sm-6 gsc_col-md-4 cardColumn']")

# Extract the text content from elements
car_details = [car.text for car in car_elements]

# Close the browser
driver.quit()

# Initialize list for structured data
structured_data = []

# Process extracted details
for detail in car_details:
    lines = detail.split("\n")  # Split text into lines
    
    try:
        year_and_name = lines[0].split(" ", 1)  # Extract Year and Car Name
        year = year_and_name[0]
        car_name = year_and_name[1]
        
        if "•" in lines[1]:
            details = [item.strip() for item in lines[1].split("•")]
            if len(details) == 3:
                mileage, fuel_type, transmission = details
            elif len(details) == 2:
                mileage, fuel_type = details
                transmission = ""
            else:
                mileage = details[0]
                fuel_type = transmission = ""
        else:
            mileage = fuel_type = transmission = ""
        
        mileage = mileage.replace("kms", "").strip()  # Clean mileage
        
        price = lines[2].replace("₹", "").replace("Lakh", "").strip() if len(lines) > 2 else ""
        
        location = lines[-1] if len(lines) > 3 else ""
        
        structured_data.append({
            "Year": year,
            "Car Name": car_name,
            "Mileage (kms)": mileage,
            "Fuel Type": fuel_type,
            "Transmission": transmission,
            "Price (Lakh)": price,
            "Location": location
        })
    except Exception as e:
        print(f"Error processing detail: {detail}\nError: {e}")

# Create DataFrame
car3_df = pd.DataFrame(structured_data)

# Save to CSV
car3_df.to_csv('ahmedabad_used_cars.csv', index=False)

print(car3_df)

In [9]:
print(car3_df)

      Year                                   Car Name Mileage (kms) Fuel Type  \
0     2023                   BMW X1 sDrive18d M Sport        20,000    Diesel
1     2018                    Toyota Yaris J CVT BSIV        56,000    Petrol
2     2018              Maruti Vitara Brezza ZDi Plus        78,000    Diesel
3     2021                    Kia Sonet HTX Turbo iMT        30,159    Petrol
4     2022            Tata Tigor EV XZ Plus Dual Tone        30,000  Electric
...    ...                                        ...           ...       ...
1369  2018  Mercedes-Benz GLA Class Urban Edition 200        35,000    Petrol
1370  2014       Jaguar XF 3.0 Litre S Premium Luxury        47,000    Diesel
1371  2015         Land Rover Range Rover Evoque Pure        71,000    Diesel
1372  2015                     Audi A6 35 TDI Premium        54,000    Diesel
1373  2015                          BMW Z4 sDrive 35i        35,000    Petrol

     Transmission Price (Lakh)                    Location
0       Automatic           50                   Ahmedabad
1       Automatic         3.65  Sahil Residency, Ahmedabad
2          Manual       79,000          Alampur, Ahmedabad
3       Automatic         8.60             Gota, Ahmedabad
4       Automatic         8.80                   Ahmedabad
...           ...          ...                         ...
1369    Automatic        23.90       Chattarpur, New Delhi
1370    Automatic        16.90       Chattarpur, New Delhi
1371    Automatic        22.90       Chattarpur, New Delhi
1372    Automatic        14.90       Chattarpur, New Delhi
1373    Automatic        46.90       Chattarpur, New Delhi

[1374 rows x 7 columns]

In [6]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
import time

# Initialize WebDriver
driver = webdriver.Chrome()
driver.get("https://www.cardekho.com/used-cars+in+kolkata")  # Chennai Cars Page
driver.maximize_window()
time.sleep(5)  # Allow page to load



# Scroll until the end of the page
last_height = driver.execute_script("return document.body.scrollHeight")  # Get initial page height
scroll_attempts = 0

while True:
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(3)  # Allow time for new content to load
    
    new_height = driver.execute_script("return document.body.scrollHeight")
    if new_height == last_height:
        scroll_attempts += 1
        if scroll_attempts > 5:  # Stop after 5 failed attempts to load more content
            break
    else:
        scroll_attempts = 0  # Reset if new content loads

    last_height = new_height

# Find elements containing car details
car_elements = driver.find_elements(By.XPATH, "//div[@class='gsc_col-xs-12 gsc_col-sm-6 gsc_col-md-4 cardColumn']")

# Extract the text content from elements
car_details = [car.text for car in car_elements]

# Close the browser
driver.quit()

# Initialize list for structured data
structured_data = []

# Process extracted details
for detail in car_details:
    lines = detail.split("\n")  # Split text into lines
    
    try:
        year_and_name = lines[0].split(" ", 1)  # Extract Year and Car Name
        year = year_and_name[0]
        car_name = year_and_name[1]
        
        if "•" in lines[1]:
            details = [item.strip() for item in lines[1].split("•")]
            if len(details) == 3:
                mileage, fuel_type, transmission = details
            elif len(details) == 2:
                mileage, fuel_type = details
                transmission = ""
            else:
                mileage = details[0]
                fuel_type = transmission = ""
        else:
            mileage = fuel_type = transmission = ""
        
        mileage = mileage.replace("kms", "").strip()  # Clean mileage
        
        price = lines[2].replace("₹", "").replace("Lakh", "").strip() if len(lines) > 2 else ""
        
        location = lines[-1] if len(lines) > 3 else ""
        
        structured_data.append({
            "Year": year,
            "Car Name": car_name,
            "Mileage (kms)": mileage,
            "Fuel Type": fuel_type,
            "Transmission": transmission,
            "Price (Lakh)": price,
            "Location": location
        })
    except Exception as e:
        print(f"Error processing detail: {detail}\nError: {e}")

# Create DataFrame
car4_df = pd.DataFrame(structured_data)

# Save to CSV
car4_df.to_csv('kolkata_used_cars.csv', index=False)

# Print DataFrame
print(car4_df)

      Year                     Car Name Mileage (kms) Fuel Type Transmission  \
0     2024       BMW X5 xDrive40i xLine         3,406    Petrol    Automatic
1     2021            Renault Kiger RXL        36,756    Petrol       Manual
2     2022     Renault KWID 1.0 RXT AMT        20,024    Petrol    Automatic
3     2012          Maruti Alto 800 LXi        42,015    Petrol       Manual
4     2016           BMW 7 Series 730Ld        20,000    Diesel    Automatic
...    ...                          ...           ...       ...          ...
1097  2013            Hyundai i20 Magna        48,018    Petrol       Manual
1098  2010        Hyundai i10 Magna 1.2        46,006    Petrol       Manual
1099  2014         Honda City i DTEC VX      1,50,000    Diesel       Manual
1100  2021  Maruti Wagon R VXI 1.2 BSIV        22,006    Petrol       Manual
1101  2013            Hyundai i20 Magna        48,018    Petrol       Manual

     Price (Lakh)                Location
0              90  Vaishya Sabha, Kolkata
1            4.60        Alipore, Kolkata
2            4.25       Garia Bt, Kolkata
3            1.55       Garia Bt, Kolkata
4              35          Kasba, Kolkata
...           ...                     ...
1097         2.75       Garia Bt, Kolkata
1098         1.55       Garia Bt, Kolkata
1099         2.50                 Kolkata
1100         4.75       Garia Bt, Kolkata
1101         2.75       Garia Bt, Kolkata

[1102 rows x 7 columns]

In [3]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
import time

# Initialize WebDriver
driver = webdriver.Chrome()
driver.get("https://www.cardekho.com/used-cars+in+delhi-ncr") 
driver.maximize_window()
time.sleep(5)  # Allow page to load

# Scroll until the end of the page
last_height = driver.execute_script("return document.body.scrollHeight")  # Get initial page height
scroll_attempts = 0

while True:
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(3)  # Allow time for new content to load
    
    new_height = driver.execute_script("return document.body.scrollHeight")
    
    if new_height == last_height:
        scroll_attempts += 1
        if scroll_attempts > 3:  # Stop after 3 failed attempts to load more content
            break
    else:
        scroll_attempts = 0  # Reset if new content loads

    last_height = new_height

try:
    # Find elements containing car details
    car_elements = driver.find_elements(By.XPATH, "//div[contains(@class,'cardColumn')]")

    # Initialize list for structured data
    structured_data = []

    for car in car_elements:
        details = car.text.split("\n")  # Extract text from each element
        
        try:
            # Extract Year and Car Name
            year_and_name = details[0].split(" ", 1)  # Year is first part
            year = year_and_name[0]
            car_name = year_and_name[1] if len(year_and_name) > 1 else ""

            # Extract Mileage, Fuel Type, Transmission
            mileage, fuel_type, transmission = "", "", ""

            if "•" in details[1]:
                specs = [x.strip() for x in details[1].split("•")]
                if len(specs) >= 3:
                    mileage, fuel_type, transmission = specs[:3]
                elif len(specs) == 2:
                    mileage, fuel_type = specs
                elif len(specs) == 1:
                    mileage = specs[0]

            # Clean Mileage Data
            mileage = mileage.replace("kms", "").strip()

            # Extract Price (handling missing values)
            price = ""
            for item in details:
                if "₹" in item:
                    price = item.replace("₹", "").replace("Lakh", "").strip()
                    break

            # Extract Location (Assumed last line contains location)
            location = details[-1] if len(details) > 3 else ""

            structured_data.append({
                "Year": year,
                "Car Name": car_name,
                "Mileage (kms)": mileage,
                "Fuel Type": fuel_type,
                "Transmission": transmission,
                "Price (Lakh)": price,
                "Location": location
            })

        except Exception as e:
            print(f"Error processing car details: {details}\nError: {e}")

finally:
    driver.quit()  # Always close the browser

# Create DataFrame
car_df = pd.DataFrame(structured_data)

# Save to CSV
car_df.to_csv('delhi_used_cars.csv', index=False)
print(car_df)

      Year                                    Car Name Mileage (kms)  \
0       AD
1     2017                         Honda City i VTEC S        42,050
2     2024                   Hyundai Venue S 2023-2025         3,600
3     2024  Mercedes-Benz A-Class Limousine A 200 BSVI        10,000
4     2021                          Kia Sonet HTK BSVI        67,000
...    ...                                         ...           ...
3476  2024          Mercedes-Benz GLS 400d 4MATIC BSVI         2,500
3477  2019            Ford Endeavour Titanium Plus 4X2        63,000
3478  2016                    Hyundai Grand i10 Sportz        65,000
3479  2020             Renault KWID Climber 1.0 MT Opt        37,000
3480  2019                Hyundai i20 Sportz Plus BSIV        49,000

     Fuel Type Transmission Price (Lakh)                      Location
0                                     25           Sector 21e, Gurgaon
1       Petrol       Manual         5.75        Ashok Vihar, New Delhi
2       Petrol       Manual         9.25      Krishna Nagar, New Delhi
3       Petrol    Automatic        39.75     Dilshad Garden, New Delhi
4       Petrol       Manual         7.25          Pitampura, New Delhi
...        ...          ...          ...                           ...
3476    Diesel    Automatic   1.35 Crore        Ashok Vihar, New Delhi
3477    Diesel    Automatic        23.90       Ramesh Nagar, New Delhi
3478    Petrol       Manual         3.80        Preet Vihar, New Delhi
3479    Petrol       Manual         4.15       Ip Extension, New Delhi
3480    Petrol       Manual         5.45  Dr.mukerjee Nagar, New Delhi

[3481 rows x 7 columns]

In [4]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
import time

# Initialize WebDriver
driver = webdriver.Chrome()
driver.get("https://www.cardekho.com/used-cars+in+mumbai") 
driver.maximize_window()
time.sleep(5)  # Allow page to load

# Scroll until the end of the page
last_height = driver.execute_script("return document.body.scrollHeight")  # Get initial page height
scroll_attempts = 0

while True:
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(3)  # Allow time for new content to load
    
    new_height = driver.execute_script("return document.body.scrollHeight")
    
    if new_height == last_height:
        scroll_attempts += 1
        if scroll_attempts > 3:  # Stop after 3 failed attempts to load more content
            break
    else:
        scroll_attempts = 0  # Reset if new content loads

    last_height = new_height

try:
    # Find elements containing car details
    car_elements = driver.find_elements(By.XPATH, "//div[contains(@class,'cardColumn')]")

    # Initialize list for structured data
    structured_data = []

    for car in car_elements:
        details = car.text.split("\n")  # Extract text from each element
        
        try:
            # Extract Year and Car Name
            year_and_name = details[0].split(" ", 1)  # Year is first part
            year = year_and_name[0]
            car_name = year_and_name[1] if len(year_and_name) > 1 else ""

            # Extract Mileage, Fuel Type, Transmission
            mileage, fuel_type, transmission = "", "", ""

            if "•" in details[1]:
                specs = [x.strip() for x in details[1].split("•")]
                if len(specs) >= 3:
                    mileage, fuel_type, transmission = specs[:3]
                elif len(specs) == 2:
                    mileage, fuel_type = specs
                elif len(specs) == 1:
                    mileage = specs[0]

            # Clean Mileage Data
            mileage = mileage.replace("kms", "").strip()

            # Extract Price (handling missing values)
            price = ""
            for item in details:
                if "₹" in item:
                    price = item.replace("₹", "").replace("Lakh", "").strip()
                    break

            # Extract Location (Assumed last line contains location)
            location = details[-1] if len(details) > 3 else ""

            structured_data.append({
                "Year": year,
                "Car Name": car_name,
                "Mileage (kms)": mileage,
                "Fuel Type": fuel_type,
                "Transmission": transmission,
                "Price (Lakh)": price,
                "Location": location
            })

        except Exception as e:
            print(f"Error processing car details: {details}\nError: {e}")

finally:
    driver.quit()  # Always close the browser

# Create DataFrame
car0_df = pd.DataFrame(structured_data)

# Save to CSV
car0_df.to_csv('mumbai_used_cars.csv', index=False)
print(car0_df)

      Year                           Car Name Mileage (kms) Fuel Type  \
0     2023   Audi Q3 Sportback 40TFSI Quattro        10,000    Petrol
1     2008          Hyundai i10 Sportz 1.2 AT        52,000    Petrol
2     2019            Renault Triber RXZ BSIV        19,000    Petrol
3     2019       Hyundai i20 Sportz Plus BSIV        25,000    Petrol
4     2020              Tata Nexon EV XZ Plus        28,000  Electric
...    ...                                ...           ...       ...
3556  2014           Hyundai Verna SX CRDi AT        36,000    Diesel
3557  2023  Hyundai Grand i10 Nios Sportz CNG        21,000       CNG
3558  2023        Renault Kiger RXZ Turbo CVT        20,000    Petrol
3559  2017               Honda City i VTEC SV        55,897    Petrol
3560  2020     Maruti Swift Dzire ZXI AT BSVI        32,000    Petrol

     Transmission Price (Lakh)                Location
0       Automatic           41                  Mumbai
1       Automatic         1.68    Andheri East, Mumbai
2          Manual         5.45    Matunga West, Mumbai
3          Manual         6.75  Ghatkopar East, Mumbai
4       Automatic         9.99   Borivali West, Mumbai
...           ...          ...                     ...
3556    Automatic         5.50      Malad West, Mumbai
3557       Manual            8      Vitthalwadi, Thane
3558    Automatic         8.95   Goregaon West, Mumbai
3559       Manual         5.60      Malad West, Mumbai
3560    Automatic         7.25    Andheri East, Mumbai

[3561 rows x 7 columns]

In [ ]:
#aws s3 uploading

In [1]:
pip install boto3

Collecting boto3
  Downloading boto3-1.36.12-py3-none-any.whl (139 kB)
     ------------------------------------ 139.2/139.2 kB 749.6 kB/s eta 0:00:00
Collecting botocore<1.37.0,>=1.36.12
  Downloading botocore-1.36.12-py3-none-any.whl (13.3 MB)
     ---------------------------------------- 13.3/13.3 MB 1.0 MB/s eta 0:00:00
Collecting jmespath<2.0.0,>=0.7.1
  Downloading jmespath-1.0.1-py3-none-any.whl (20 kB)
Collecting s3transfer<0.12.0,>=0.11.0
  Downloading s3transfer-0.11.2-py3-none-any.whl (84 kB)
     ---------------------------------------- 84.2/84.2 kB 1.6 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\users\hari vignesh\appdata\roaming\python\python311\site-packages (from botocore<1.37.0,>=1.36.12->boto3) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in c:\users\hari vignesh\appdata\local\programs\python\python311\lib\site-packages (from botocore<1.37.0,>=1.36.12->boto3) (2.3.0)
Requirement already satisfied: six>=1.5 in c:\users\hari vignesh\appdata\roaming\python\python311\site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.37.0,>=1.36.12->boto3) (1.17.0)
Installing collected packages: jmespath, botocore, s3transfer, boto3
Successfully installed boto3-1.36.12 botocore-1.36.12 jmespath-1.0.1 s3transfer-0.11.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import boto3

In [4]:
access_key="AKIAX5ZI6HRQ3QZIIHE7"
secret_key="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"

In [5]:
aws=boto3.client("s3",aws_access_key_id=access_key,aws_secret_access_key=secret_key)

In [6]:
bucket=aws.list_buckets()
bucket

{'ResponseMetadata': {'RequestId': 'GQ2H2DQ5NR741G3S',
  'HostId': 'hiu/kpu8uiGtxanAIRQSpq/GBkyt9h6lU7B8U7R2h0CoqRUU3J8eoZUL7oSobdeZFtpfgjfr/QE=',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amz-id-2': 'hiu/kpu8uiGtxanAIRQSpq/GBkyt9h6lU7B8U7R2h0CoqRUU3J8eoZUL7oSobdeZFtpfgjfr/QE=',
   'x-amz-request-id': 'GQ2H2DQ5NR741G3S',
   'date': 'Tue, 04 Feb 2025 09:03:24 GMT',
   'content-type': 'application/xml',
   'transfer-encoding': 'chunked',
   'server': 'AmazonS3'},
  'RetryAttempts': 0},
 'Buckets': [{'Name': 'mrbucketaws',
   'CreationDate': datetime.datetime(2025, 2, 3, 3, 50, 50, tzinfo=tzutc())}],
 'Owner': {'DisplayName': 'mr.vicky55islucky',
  'ID': '630b8ab3171e5b4b8ecea5ab1b2ee14af046606ab5780e02964d375788a4c70d'}}

In [7]:
bucket["Buckets"][0]["Name"]

'mrbucketaws'

In [8]:
bucket_file=aws.list_objects_v2(Bucket=bucket["Buckets"][0]["Name"])
bucket_file

{'ResponseMetadata': {'RequestId': 'V32SCNKA2VZ8BK8N',
  'HostId': '6jZLdTkPFQvEUP2G0YLyEjDY1DbcIFBBuCbzL0XaROwzXzjHJADMnGUcxXMtrxLb8meOG63RMJc=',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amz-id-2': '6jZLdTkPFQvEUP2G0YLyEjDY1DbcIFBBuCbzL0XaROwzXzjHJADMnGUcxXMtrxLb8meOG63RMJc=',
   'x-amz-request-id': 'V32SCNKA2VZ8BK8N',
   'date': 'Tue, 04 Feb 2025 09:06:19 GMT',
   'x-amz-bucket-region': 'ap-south-1',
   'content-type': 'application/xml',
   'transfer-encoding': 'chunked',
   'server': 'AmazonS3'},
  'RetryAttempts': 1},
 'IsTruncated': False,
 'Contents': [{'Key': 'ahmedabad_used_cars.csv',
   'LastModified': datetime.datetime(2025, 2, 3, 3, 54, tzinfo=tzutc()),
   'ETag': '"a804ddb6f4e1e398c8392facbde1dabe"',
   'ChecksumAlgorithm': ['CRC64NVME'],
   'ChecksumType': 'FULL_OBJECT',
   'Size': 110864,
   'StorageClass': 'STANDARD'},
  {'Key': 'bengalure_car_details.csv',
   'LastModified': datetime.datetime(2025, 2, 3, 3, 54, 1, tzinfo=tzutc()),
   'ETag': '"1e3189d2bff472085edd964037d1c7c5"',
   'ChecksumAlgorithm': ['CRC64NVME'],
   'ChecksumType': 'FULL_OBJECT',
   'Size': 249007,
   'StorageClass': 'STANDARD'},
  {'Key': 'harivicky/',
   'LastModified': datetime.datetime(2025, 2, 3, 3, 52, 53, tzinfo=tzutc()),
   'ETag': '"d41d8cd98f00b204e9800998ecf8427e"',
   'Size': 0,
   'StorageClass': 'STANDARD'}],
 'Name': 'mrbucketaws',
 'Prefix': '',
 'MaxKeys': 1000,
 'EncodingType': 'url',
 'KeyCount': 3}

In [10]:
import os

bucket_name = "mrbucketaws"
folder_name = "harivicky/"
file_paths = [
    r"C:\Users\Hari Vignesh\Desktop\Hari Data Scientist Guvi\Data Science course guvi\cardekho project\ahmedabad_used_cars.csv",
    r"C:\Users\Hari Vignesh\Desktop\Hari Data Scientist Guvi\Data Science course guvi\cardekho project\bengalure_car_details.csv",
    r"C:\Users\Hari Vignesh\Desktop\Hari Data Scientist Guvi\Data Science course guvi\cardekho project\chennai_used_cars.csv",
    r"C:\Users\Hari Vignesh\Desktop\Hari Data Scientist Guvi\Data Science course guvi\cardekho project\delhi_used_cars.csv",
    r"C:\Users\Hari Vignesh\Desktop\Hari Data Scientist Guvi\Data Science course guvi\cardekho project\hyderabad_car_details.csv",
    r"C:\Users\Hari Vignesh\Desktop\Hari Data Scientist Guvi\Data Science course guvi\cardekho project\kolkata_used_cars.csv",
    r"C:\Users\Hari Vignesh\Desktop\Hari Data Scientist Guvi\Data Science course guvi\cardekho project\mumbai_used_cars.csv"
]

for file_path in file_paths:
    file_name = os.path.basename(file_path)  # Extract file name from path
    s3_aws_name = folder_name + file_name  # Set destination in S3

    with open(file_path, "rb") as f:
        aws.upload_fileobj(f, bucket_name, s3_aws_name)
        print(f"Uploaded {file_name} to S3 as {s3_aws_name}")

Uploaded ahmedabad_used_cars.csv to S3 as harivicky/ahmedabad_used_cars.csv
Uploaded bengalure_car_details.csv to S3 as harivicky/bengalure_car_details.csv
Uploaded chennai_used_cars.csv to S3 as harivicky/chennai_used_cars.csv
Uploaded delhi_used_cars.csv to S3 as harivicky/delhi_used_cars.csv
Uploaded hyderabad_car_details.csv to S3 as harivicky/hyderabad_car_details.csv
Uploaded kolkata_used_cars.csv to S3 as harivicky/kolkata_used_cars.csv
Uploaded mumbai_used_cars.csv to S3 as harivicky/mumbai_used_cars.csv